
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Avishka
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.setLocationRelativeTo(null);
        label();
        combo();
    }

    public void label(){
         try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            Statement st = con.createStatement();
            ResultSet rs= st.executeQuery("select count(regNo) from registration");
            if(rs.next())
            {
                int regNo = rs.getInt(1);
                regNo = regNo+1;
                String str = String.valueOf(regNo);
                jLabel5.setText(str);
            }
            else
                jLabel5.setText("1");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void combo(){
        int i=0;    
        try
        {
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            Statement st = con.createStatement();
            ResultSet rs= st.executeQuery("select * from registration");
            while(rs.next())
            {
                i=1;
                jComboBox1.addItem(rs.getString(i));
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nictxt = new javax.swing.JTextField();
        contacttxt = new javax.swing.JTextField();
        parenttxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        femaleradio = new javax.swing.JRadioButton();
        maleradio = new javax.swing.JRadioButton();
        lnametxt = new javax.swing.JTextField();
        calendar = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hometxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addresstxtarea = new javax.swing.JTextArea();
        clearbtn = new javax.swing.JButton();
        registerbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Skills International");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 49));

        jPanel2.setBackground(new java.awt.Color(46, 62, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Rregistration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reg. No ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(46, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parent Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contact Number");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Parent Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        nictxt.setBackground(new java.awt.Color(108, 122, 137));
        nictxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nictxt.setForeground(new java.awt.Color(228, 241, 254));
        nictxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nictxtActionPerformed(evt);
            }
        });
        jPanel3.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 420, -1));

        contacttxt.setBackground(new java.awt.Color(108, 122, 137));
        contacttxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contacttxt.setForeground(new java.awt.Color(228, 241, 254));
        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });
        jPanel3.add(contacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, -1));

        parenttxt.setBackground(new java.awt.Color(108, 122, 137));
        parenttxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        parenttxt.setForeground(new java.awt.Color(228, 241, 254));
        parenttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parenttxtActionPerformed(evt);
            }
        });
        jPanel3.add(parenttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 420, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 600, 140));

        jPanel4.setBackground(new java.awt.Color(46, 62, 80));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth ");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name ");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fist Name");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        fnametxt.setBackground(new java.awt.Color(108, 122, 137));
        fnametxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fnametxt.setForeground(new java.awt.Color(228, 241, 254));
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        jPanel4.add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 420, -1));

        femaleradio.setBackground(new java.awt.Color(108, 122, 137));
        buttonGroup1.add(femaleradio);
        femaleradio.setForeground(new java.awt.Color(228, 241, 254));
        femaleradio.setText("Female");
        femaleradio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femaleradioItemStateChanged(evt);
            }
        });
        femaleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradioActionPerformed(evt);
            }
        });
        jPanel4.add(femaleradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        maleradio.setBackground(new java.awt.Color(108, 122, 137));
        buttonGroup1.add(maleradio);
        maleradio.setForeground(new java.awt.Color(228, 241, 254));
        maleradio.setText("Male");
        maleradio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maleradioItemStateChanged(evt);
            }
        });
        jPanel4.add(maleradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        lnametxt.setBackground(new java.awt.Color(108, 122, 137));
        lnametxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lnametxt.setForeground(new java.awt.Color(228, 241, 254));
        lnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametxtActionPerformed(evt);
            }
        });
        jPanel4.add(lnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 420, -1));

        calendar.setBackground(new java.awt.Color(108, 122, 137));
        calendar.setForeground(new java.awt.Color(228, 241, 254));
        jPanel4.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 600, 180));

        jPanel5.setBackground(new java.awt.Color(46, 62, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile Phone");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E mail ");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Home Phone");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Addess");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        hometxt.setBackground(new java.awt.Color(108, 122, 137));
        hometxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hometxt.setForeground(new java.awt.Color(228, 241, 254));
        hometxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hometxtActionPerformed(evt);
            }
        });
        jPanel5.add(hometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 140, -1));

        emailtxt.setBackground(new java.awt.Color(108, 122, 137));
        emailtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(228, 241, 254));
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel5.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 420, -1));

        mobiletxt.setBackground(new java.awt.Color(108, 122, 137));
        mobiletxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mobiletxt.setForeground(new java.awt.Color(228, 241, 254));
        mobiletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiletxtActionPerformed(evt);
            }
        });
        jPanel5.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, -1));

        addresstxtarea.setBackground(new java.awt.Color(108, 122, 137));
        addresstxtarea.setColumns(20);
        addresstxtarea.setForeground(new java.awt.Color(228, 241, 254));
        addresstxtarea.setRows(5);
        jScrollPane2.setViewportView(addresstxtarea);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 420, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 600, 180));

        clearbtn.setBackground(new java.awt.Color(0, 153, 52));
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 100, 40));

        registerbtn.setBackground(new java.awt.Color(34, 167, 240));
        registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        registerbtn.setText("Rregister");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 100, 40));

        updatebtn.setBackground(new java.awt.Color(153, 0, 153));
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel2.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 100, 40));

        deletebtn.setBackground(new java.awt.Color(242, 38, 19));
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel2.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 100, 40));

        jComboBox1.setBackground(new java.awt.Color(108, 122, 137));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(228, 241, 254));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Already Registerd No." }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 160, -1));

        jLabel5.setBackground(new java.awt.Color(248, 148, 6));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 148, 6));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 660, 640));

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 51));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("-Exit-");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void femaleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleradioActionPerformed

    private void nictxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nictxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nictxtActionPerformed

    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttxtActionPerformed

    private void hometxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hometxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hometxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void mobiletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiletxtActionPerformed

    private void parenttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parenttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parenttxtActionPerformed

    private void lnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        String regNo=(String)jLabel5.getText();
        String firstName=fnametxt.getText();
        String lastname = lnametxt.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        String dateofBirth = sdf.format(calendar.getDate());
        String gender = maleradio.getText();
        String address = addresstxtarea.getText();
        String email = emailtxt.getText();
        String mobilePhone = mobiletxt.getText();
        String homePhone = hometxt.getText();
        String parentName = parenttxt.getText();
        String nic = nictxt.getText();
        String contactNo = contacttxt.getText();
        
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            PreparedStatement ps = con.prepareStatement("INSERT INTO registration VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, regNo);
            ps.setString(2, firstName);
            ps.setString(3, lastname);
            ps.setString(4, dateofBirth);
            ps.setString(5, gender);
            ps.setString(6, address);
            ps.setString(7, email);
            ps.setString(8, mobilePhone);
            ps.setString(9, homePhone);
            ps.setString(10, parentName);
            ps.setString(11, nic);
            ps.setString(12, contactNo);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Added Successfully !! ","Register Student",JOptionPane.INFORMATION_MESSAGE);
            clear();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
         label();
        combo();
    }//GEN-LAST:event_registerbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
        
        
    }//GEN-LAST:event_clearbtnActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        String firstName=fnametxt.getText();
        String lastName=lnametxt.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        String dateofBirth = sdf.format(calendar.getDate());
        String email = emailtxt.getText();
        String address = addresstxtarea.getText();
        String mobilePhone =mobiletxt.getText();
        String homePhone = hometxt.getText();
        String parentName = parenttxt.getText();
        String nic = nictxt.getText();
        String contactNo =contacttxt.getText();
        
        String regNo = (String)jComboBox1.getSelectedItem();
          
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            PreparedStatement ps = con.prepareStatement("UPDATE registration SET  firstName=?, lastName=? ,dateofBirth=? ,gender=?, address=?, email=?, mobilePhone=?, homePhone=?, parentName=?, nic=?, contactNo=? where regNo='"+regNo+"'");
            
            //ps.setString(1, regNo);
            ps.setString(1, firstName);
            ps.setString(2, lastName);
           
            ps.setString(3, dateofBirth);
            ps.setString(4, gender);
            ps.setString(5, address);
            ps.setString(6, email);
            ps.setString(7, mobilePhone);
            ps.setString(8, homePhone);
            ps.setString(9, parentName);
            ps.setString(10, nic);
            ps.setString(11, contactNo);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            clear();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_updatebtnActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       String regNo = (String)jComboBox1.getSelectedItem();
       int i =0;
       ResultSet rs;
       
       try
       {
          Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            PreparedStatement ps = con.prepareStatement("select firstName, lastName, dateofBirth, gender, address, email, mobilePhone, homePhone, parentName, nic, contactNo from registration where regNo=?");
            ps.setString(1, regNo);
            
            rs = (ResultSet) (Resultset) ps.executeQuery();
            
            while(rs.next())
            {
                fnametxt.setText(rs.getString("firstName"));
                lnametxt.setText(rs.getString("lastName"));
                calendar.setDate(rs.getDate("dateofBirth"));
                String gender = rs.getString("gender");
                {
                    if(gender.equals("female")){
                        maleradio.setSelected(false);
                        femaleradio.setSelected(false);
                    }else{
                        femaleradio.setSelected(false);
                        maleradio.setSelected(true);
                    }
                }
                addresstxtarea.setText(rs.getString("address"));
                emailtxt.setText(rs.getString("email"));
                mobiletxt.setText(rs.getString("mobilePhone"));
                hometxt.setText(rs.getString("homePhone"));
                parenttxt.setText(rs.getString("parentName"));
                nictxt.setText(rs.getString("nic"));
                contacttxt.setText(rs.getString("contactNo"));
                        
                    }
                }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
            }
       
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void maleradioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maleradioItemStateChanged
        // TODO add your handling code here:
        gender = "male";
    }//GEN-LAST:event_maleradioItemStateChanged

    private void femaleradioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femaleradioItemStateChanged
        // TODO add your handling code here:
        gender = "female";
    }//GEN-LAST:event_femaleradioItemStateChanged

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
          String regNo = (String)jComboBox1.getSelectedItem();
             
             int a= JOptionPane.showConfirmDialog(this,"Do you really want to Delete this Record...?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
     if(a==0)
     {
        
         
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
            PreparedStatement ps = con.prepareStatement("delete from registration where regNo=?");
            ps.setString(1, regNo);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Deleted");
            clear();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        label();
        combo(); 
     }
        
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstxtarea;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel exit;
    private javax.swing.JRadioButton femaleradio;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField hometxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JLabel logout;
    private javax.swing.JRadioButton maleradio;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nictxt;
    private javax.swing.JTextField parenttxt;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        
        fnametxt.setText("");
        lnametxt.setText("");
        calendar.setCalendar(null);
        maleradio.setSelected(false);
        femaleradio.setSelected(false);
        addresstxtarea.setText("");
        emailtxt.setText("");
        mobiletxt.setText("");
        hometxt.setText("");
        parenttxt.setText("");
        nictxt.setText("");
        contacttxt.setText("");
        
        jComboBox1.setSelectedIndex(0);
        buttonGroup1.clearSelection();
    }
    private String gender;
}
