
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Avishka
 */
public class Splashscreen extends javax.swing.JFrame {

    /**
     * Creates new form Splashscreen
     */
    public Splashscreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loadinglable = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(46, 62, 80));
        setUndecorated(true);

        backgroundpanel.setBackground(new java.awt.Color(46, 62, 80));
        backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Skills International");
        backgroundpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 49));

        loadinglable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadinglable.setForeground(new java.awt.Color(255, 255, 255));
        loadinglable.setText("Loading...");
        backgroundpanel.add(loadinglable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        loadingvalue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        loadingvalue.setText("0%");
        backgroundpanel.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 30, -1));

        loadingbar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroundpanel.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 580, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avishka\\Documents\\NetBeansProjects\\mavenproject20\\src\\main\\java\\image\\bachelors-degree (5).png")); // NOI18N
        backgroundpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 270, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        Splashscreen sc = new Splashscreen();
        sc.setVisible(true);
        
        Login login = new Login();
        
        try{
            
            for(int i=0;i<=100;i++){
                
            Thread.sleep(100);
            sc.loadingvalue.setText(i+"%");
            
            if(i==10){
              sc.loadinglable.setText("Turning on Modules...");
            }
            if(i==30){
              sc.loadinglable.setText("Loading Modules...");
            }
            if(i==50){
              sc.loadinglable.setText("Connecting to Database...");
            }
            if(i==70){
              sc.loadinglable.setText("Connection Successfull !");
            }
            if(i==90){
              sc.loadinglable.setText("Launching Application...");
            }
            sc.loadingbar.setValue(i);
           }
        }catch (Exception e){
            
            
        }
        sc.setVisible(false);
        login.setVisible(true);
        
        sc.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadinglable;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables

   }